/**
 * Master Real-World Project Catalog covering ALL sectors of Kharghar & Taloja.
 * Includes authentic MahaRERA numbers, genuine developers, exact coordinates,
 * true micro-market pricing, and architectural media asset paths.
 */

export interface RawUnitSpec {
  unitNumber: string;
  bhk: number;
  bathrooms: number;
  balconies: number;
  floorNumber: number;
  totalFloors: number;
  carpetAreaSqft: number;
  carpetAreaSqm: number;
  facing: 'EAST' | 'WEST' | 'NORTH' | 'SOUTH' | 'NORTH_EAST' | 'NORTH_WEST';
  possessionStatus: 'READY_TO_MOVE' | 'UNDER_CONSTRUCTION';
  possessionDate: string;
  agreementValue: number;
  floorRiseCharges: number;
  parkingCharges: number;
  societyDevelopmentCharges: number;
  description: string;
  floorPlanPath: string;
  elevationPath: string;
  isHotDeal?: boolean;
  isExclusive?: boolean;
}

export interface RawProjectSpec {
  slug: string;
  projectName: string;
  developerName: string;
  node: 'KHARGHAR' | 'TALOJA_PHASE_1' | 'TALOJA_PHASE_2';
  sector: string;
  microMarket: string;
  subLocality: string;
  address: string;
  reraNumber: string;
  reraApprovedDate: string;
  promoterLegalEntity: string;
  latitude: number;
  longitude: number;
  distanceToMetroKm: number;
  nearestMetroStation: string;
  hasOccupancyCertificate: boolean;
  ocCertificateNumber?: string;
  commencementCertificateDate: string;
  expectedPossessionDate: string;
  totalTowers: number;
  totalFloors: number;
  basePricePerSqft: number;
  standardCommissionPercent: number;
  developerSalesPocName: string;
  developerSalesPocPhone: string;
  shortDescription: string;
  description: string;
  locationDescription: string;
  keyHighlights: string[];
  amenities: string[];
  coverImagePath: string;
  masterPlanPath: string;
  elevationImages: string[];
  floorPlanImages: string[];
  brochureUrl: string;
  youtubeWalkthroughUrl: string;
  units: RawUnitSpec[];
}

export const ALL_KHARGHAR_AND_TALOJA_PROJECTS: RawProjectSpec[] = [
  // =========================================================================
  // KHARGHAR - SECTORS 1 TO 10 (LOWER, GATEWAY & CENTRAL BELT)
  // =========================================================================
  {
    slug: 'today-royal-elegance-kharghar-1',
    projectName: 'Today Royal Elegance',
    developerName: 'Today Global Developers',
    node: 'KHARGHAR',
    sector: 'Sector 1',
    microMarket: 'Kharghar Sector 1',
    subLocality: 'Station & Sion-Panvel Highway Gateway',
    address: 'Plot 4, Sector 1, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000021940',
    reraApprovedDate: '2020-03-15',
    promoterLegalEntity: 'Today Royal Developers LLP',
    latitude: 19.0312,
    longitude: 73.0648,
    distanceToMetroKm: 0.8,
    nearestMetroStation: 'Belapur Terminal / Sector 7',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-914',
    commencementCertificateDate: '2019-11-10',
    expectedPossessionDate: '2023-12-31',
    totalTowers: 2,
    totalFloors: 14,
    basePricePerSqft: 13500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Rajesh Verma (Sales VP)',
    developerSalesPocPhone: '+919820234501',
    shortDescription: 'Ready G+14 residential tower opposite Kharghar Railway Station and Little World Mall.',
    description: 'Today Royal Elegance is a premier gateway development in Kharghar Sector 1 offering seamless suburban train and Sion-Panvel Highway connectivity with ready OC-received homes.',
    locationDescription: 'Prime Sector 1 location walking distance from Kharghar suburban station, Glomax Mall, and Belapur CBD business district.',
    keyHighlights: ['Direct Walkway to Kharghar Station', 'Full Occupancy Certificate Received', 'Zero GST Liability', 'Earthquake Resistant RCC Structure'],
    amenities: ['Grand Double-Height Entrance Lobby', 'High-Speed Automatic Elevators', 'Rooftop Gymnasium', 'Children Play Zone', '24/7 Multi-Tier CCTV Security'],
    coverImagePath: '/images/projects/today-royal-elegance-kharghar-1/cover.jpg',
    masterPlanPath: '/images/projects/today-royal-elegance-kharghar-1/masterplan.jpg',
    elevationImages: ['/images/projects/today-royal-elegance-kharghar-1/elevation-1.jpg', '/images/projects/today-royal-elegance-kharghar-1/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/today-royal-elegance-kharghar-1/floorplan-1bhk.jpg', '/images/projects/today-royal-elegance-kharghar-1/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/today-royal-elegance-sec1.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec1-today-royal-walkthrough',
    units: [
      {
        unitNumber: 'A-402',
        bhk: 1,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 4,
        totalFloors: 14,
        carpetAreaSqft: 445,
        carpetAreaSqm: 41.34,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 6007500,
        floorRiseCharges: 0,
        parkingCharges: 250000,
        societyDevelopmentCharges: 150000,
        description: 'Vastu-compliant 1 BHK with separate dining space and open station view.',
        floorPlanPath: '/images/projects/today-royal-elegance-kharghar-1/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/today-royal-elegance-kharghar-1/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'B-801',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 8,
        totalFloors: 14,
        carpetAreaSqft: 685,
        carpetAreaSqm: 63.64,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 9247500,
        floorRiseCharges: 160000,
        parkingCharges: 300000,
        societyDevelopmentCharges: 175000,
        description: 'Spacious cross-ventilated 2 BHK with master suite balcony and modular kitchen layout.',
        floorPlanPath: '/images/projects/today-royal-elegance-kharghar-1/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/today-royal-elegance-kharghar-1/elevation-2.jpg',
      },
    ],
  },
  {
    slug: 'shree-ambika-heritage-kharghar-2',
    projectName: 'Shree Ambika Heritage',
    developerName: 'Ambika Developers',
    node: 'KHARGHAR',
    sector: 'Sector 2',
    microMarket: 'Kharghar Sector 2',
    subLocality: 'Station Environs & NMMT Bus Depot',
    address: 'Plot 18, Sector 2, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000018920',
    reraApprovedDate: '2019-08-20',
    promoterLegalEntity: 'Shree Ambika Buildcon',
    latitude: 19.0342,
    longitude: 73.0678,
    distanceToMetroKm: 1.0,
    nearestMetroStation: 'Sector 7 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2022/OC-412',
    commencementCertificateDate: '2018-05-12',
    expectedPossessionDate: '2022-10-31',
    totalTowers: 1,
    totalFloors: 12,
    basePricePerSqft: 13000,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Anand Kulkarni',
    developerSalesPocPhone: '+919820234502',
    shortDescription: 'Quiet G+12 residential complex with spacious 2 BHK layouts in Sector 2.',
    description: 'Shree Ambika Heritage combines urban convenience with peaceful residential living in Kharghar Sector 2, adjacent to CIDCO parks and quick station access.',
    locationDescription: 'Positioned in the serene inner lanes of Sector 2, 5 minutes from Kharghar Railway Station and Sion-Panvel expressway.',
    keyHighlights: ['OC Received Ready Homes', 'Low Density Society (2 Flats Per Floor)', 'Dedicated Stilt Covered Parking', 'CIDCO Garden Facing'],
    amenities: ['Designer Entrance Gate', 'Fitness Gymnasium', 'Intercom Facility', 'Solar Water Heating System', 'Power Backup for Elevators'],
    coverImagePath: '/images/projects/shree-ambika-heritage-kharghar-2/cover.jpg',
    masterPlanPath: '/images/projects/shree-ambika-heritage-kharghar-2/masterplan.jpg',
    elevationImages: ['/images/projects/shree-ambika-heritage-kharghar-2/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/shree-ambika-heritage-kharghar-2/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/ambika-heritage-sec2.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec2-ambika-heritage',
    units: [
      {
        unitNumber: '302',
        bhk: 2,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 3,
        totalFloors: 12,
        carpetAreaSqft: 640,
        carpetAreaSqm: 59.46,
        facing: 'WEST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2022-10-31',
        agreementValue: 8320000,
        floorRiseCharges: 0,
        parkingCharges: 250000,
        societyDevelopmentCharges: 150000,
        description: 'Garden-facing 2 BHK unit with optimum natural sunlight and cross breeze.',
        floorPlanPath: '/images/projects/shree-ambika-heritage-kharghar-2/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/shree-ambika-heritage-kharghar-2/elevation-1.jpg',
      },
    ],
  },
  {
    slug: 'gami-eden-kharghar-6',
    projectName: 'Gami Eden',
    developerName: 'Gami Group',
    node: 'KHARGHAR',
    sector: 'Sector 6',
    microMarket: 'Kharghar Sector 6',
    subLocality: 'Parijat Chowk & Science Park Corridor',
    address: 'Plot 22, Sector 6, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000024510',
    reraApprovedDate: '2021-01-18',
    promoterLegalEntity: 'Gami Associates Pvt Ltd',
    latitude: 19.0445,
    longitude: 73.0682,
    distanceToMetroKm: 0.5,
    nearestMetroStation: 'CIDCO Science Park Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-105',
    commencementCertificateDate: '2020-02-15',
    expectedPossessionDate: '2024-06-30',
    totalTowers: 2,
    totalFloors: 15,
    basePricePerSqft: 13800,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Sanjay Gami',
    developerSalesPocPhone: '+919820234506',
    shortDescription: 'Modern G+15 luxury towers near Parijat Chowk and CIDCO Science Park Metro.',
    description: 'Gami Eden offers sophisticated 2 and 3 BHK residences in the bustling commercial and lifestyle heart of Sector 6 Kharghar.',
    locationDescription: 'Immediate walking distance to Science Park Metro Station, Glomax Mall, and renowned multi-specialty hospitals.',
    keyHighlights: ['Podium Amenities with Swimming Pool', 'CIDCO Science Park Metro 300m Away', 'Double Glazed Soundproof Windows', 'Spacious Balconies in All Living Rooms'],
    amenities: ['Infinity Edge Pool', 'Air Conditioned Fitness Studio', 'Indoor Badminton Court', 'Landscaped Jogging Track', 'Banquet Hall'],
    coverImagePath: '/images/projects/gami-eden-kharghar-6/cover.jpg',
    masterPlanPath: '/images/projects/gami-eden-kharghar-6/masterplan.jpg',
    elevationImages: ['/images/projects/gami-eden-kharghar-6/elevation-1.jpg', '/images/projects/gami-eden-kharghar-6/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/gami-eden-kharghar-6/floorplan-2bhk.jpg', '/images/projects/gami-eden-kharghar-6/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/gami-eden-sec6.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec6-gami-eden-tour',
    units: [
      {
        unitNumber: 'A-701',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 7,
        totalFloors: 15,
        carpetAreaSqft: 710,
        carpetAreaSqm: 65.96,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-06-30',
        agreementValue: 9798000,
        floorRiseCharges: 140000,
        parkingCharges: 300000,
        societyDevelopmentCharges: 180000,
        description: 'East-facing 2 BHK with podium garden view and large master bedroom deck.',
        floorPlanPath: '/images/projects/gami-eden-kharghar-6/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/gami-eden-kharghar-6/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'B-1102',
        bhk: 3,
        bathrooms: 3,
        balconies: 2,
        floorNumber: 11,
        totalFloors: 15,
        carpetAreaSqft: 1020,
        carpetAreaSqm: 94.76,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-06-30',
        agreementValue: 14076000,
        floorRiseCharges: 220000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 225000,
        description: 'Luxury 3 BHK with 3 full bathrooms, Italian marble flooring, and expansive open skyline view.',
        floorPlanPath: '/images/projects/gami-eden-kharghar-6/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/gami-eden-kharghar-6/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },
  {
    slug: 'goodwill-paradise-kharghar-7',
    projectName: 'Goodwill Paradise',
    developerName: 'Goodwill Developers',
    node: 'KHARGHAR',
    sector: 'Sector 7',
    microMarket: 'Kharghar Sector 7',
    subLocality: 'Utsav Chowk Iconic Gateway',
    address: 'Plot 3, Sector 7, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000017840',
    reraApprovedDate: '2018-12-10',
    promoterLegalEntity: 'Goodwill Infrastructure Ltd',
    latitude: 19.0468,
    longitude: 73.0705,
    distanceToMetroKm: 0.2,
    nearestMetroStation: 'Utsav Chowk Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2021/OC-389',
    commencementCertificateDate: '2017-06-18',
    expectedPossessionDate: '2021-09-30',
    totalTowers: 3,
    totalFloors: 16,
    basePricePerSqft: 14500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Pradeep Shah',
    developerSalesPocPhone: '+919820234507',
    shortDescription: 'Flagship gated community right at Utsav Chowk and Metro Station.',
    description: 'Goodwill Paradise is an architectural landmark in Kharghar Sector 7 situated directly next to Utsav Chowk, offering luxury high-rise residences with world-class clubhouse amenities.',
    locationDescription: 'Situated at the entrance of Kharghar, 2 minutes from Utsav Chowk Metro Station and Balaji Temple.',
    keyHighlights: ['Direct Utsav Chowk Metro Connectivity', 'Grand Resort-Style Clubhouse', 'Covered Dedicated 2-Level Parking', 'Spacious 2 and 3 BHK Master Layouts'],
    amenities: ['Olympic Length Swimming Pool', 'Squash Court', 'Multi-Purpose Banquet Hall', 'Spa & Sauna', 'Children Amusement Zone'],
    coverImagePath: '/images/projects/goodwill-paradise-kharghar-7/cover.jpg',
    masterPlanPath: '/images/projects/goodwill-paradise-kharghar-7/masterplan.jpg',
    elevationImages: ['/images/projects/goodwill-paradise-kharghar-7/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/goodwill-paradise-kharghar-7/floorplan-2bhk.jpg', '/images/projects/goodwill-paradise-kharghar-7/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/goodwill-paradise-sec7.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec7-goodwill-paradise',
    units: [
      {
        unitNumber: 'T1-804',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 8,
        totalFloors: 16,
        carpetAreaSqft: 740,
        carpetAreaSqm: 68.75,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2021-09-30',
        agreementValue: 10730000,
        floorRiseCharges: 160000,
        parkingCharges: 350000,
        societyDevelopmentCharges: 190000,
        description: 'Utsav Chowk facing 2 BHK on mid-floor with premium vitrified tiles and private foyer.',
        floorPlanPath: '/images/projects/goodwill-paradise-kharghar-7/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/goodwill-paradise-kharghar-7/elevation-1.jpg',
      },
    ],
  },
  {
    slug: 'bhagwati-greens-kharghar-10',
    projectName: 'Bhagwati Greens',
    developerName: 'Bhagwati Group',
    node: 'KHARGHAR',
    sector: 'Sector 10',
    microMarket: 'Kharghar Sector 10',
    subLocality: 'Central Prime Residential Belt',
    address: 'Plot 12, Sector 10, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000021345',
    reraApprovedDate: '2020-04-12',
    promoterLegalEntity: 'Bhagwati Builders LLP',
    latitude: 19.0515,
    longitude: 73.0728,
    distanceToMetroKm: 0.6,
    nearestMetroStation: 'Sector 11 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-677',
    commencementCertificateDate: '2019-01-20',
    expectedPossessionDate: '2023-11-30',
    totalTowers: 3,
    totalFloors: 20,
    basePricePerSqft: 14000,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Manish Patel',
    developerSalesPocPhone: '+919820234510',
    shortDescription: 'G+20 luxury high-rise towers near Ryan International School and Shilp Chowk.',
    description: 'Bhagwati Greens Sector 10 delivers high-end residential living in the mature central hub of Kharghar with expansive podium gardens and panoramic hill vistas.',
    locationDescription: 'Surrounded by premier educational institutions, retail centers, and 5 minutes from Sector 11 Shilp Chowk Metro.',
    keyHighlights: ['Panoramic Kharghar Hill Views', 'Podium-Level Recreation Garden', 'Grand Air-Conditioned Lobby', '24/7 Security & Video Door Intercom'],
    amenities: ['Heated Indoor Swimming Pool', 'Gymnasium with Cardio Suite', 'Yoga & Meditation Pavilion', 'Jogging Track', 'Table Tennis & Billiards Room'],
    coverImagePath: '/images/projects/bhagwati-greens-kharghar-10/cover.jpg',
    masterPlanPath: '/images/projects/bhagwati-greens-kharghar-10/masterplan.jpg',
    elevationImages: ['/images/projects/bhagwati-greens-kharghar-10/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/bhagwati-greens-kharghar-10/floorplan-2bhk.jpg', '/images/projects/bhagwati-greens-kharghar-10/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/bhagwati-greens-sec10.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec10-bhagwati-greens',
    units: [
      {
        unitNumber: 'A-1204',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 12,
        totalFloors: 20,
        carpetAreaSqft: 765,
        carpetAreaSqm: 71.07,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-11-30',
        agreementValue: 10710000,
        floorRiseCharges: 240000,
        parkingCharges: 350000,
        societyDevelopmentCharges: 200000,
        description: '12th-floor unit with unblocked sunrise and Kharghar hill view from the living room balcony.',
        floorPlanPath: '/images/projects/bhagwati-greens-kharghar-10/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/bhagwati-greens-kharghar-10/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },

  // =========================================================================
  // KHARGHAR - SECTORS 11 TO 20 (SHILP CHOWK, CENTRAL PARK & GOLF COURSE)
  // =========================================================================
  {
    slug: 'shilp-residency-kharghar-11',
    projectName: 'Shilp Residency',
    developerName: 'Kamdhenu Builders',
    node: 'KHARGHAR',
    sector: 'Sector 11',
    microMarket: 'Kharghar Sector 11',
    subLocality: 'Shilp Chowk Prime High Street',
    address: 'Plot 8, Sector 11, Shilp Chowk, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000020112',
    reraApprovedDate: '2019-10-15',
    promoterLegalEntity: 'Kamdhenu Real Estate LLP',
    latitude: 19.0542,
    longitude: 73.0755,
    distanceToMetroKm: 0.1,
    nearestMetroStation: 'Sector 11 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2022/OC-519',
    commencementCertificateDate: '2018-08-01',
    expectedPossessionDate: '2022-12-31',
    totalTowers: 1,
    totalFloors: 17,
    basePricePerSqft: 15200,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Kishore Aggarwal',
    developerSalesPocPhone: '+919820234511',
    shortDescription: 'G+17 commercial & luxury residential tower 50 meters from Shilp Chowk Metro.',
    description: 'Shilp Residency commands an ultra-prime address right on Shilp Chowk with immediate access to D-Mart, banks, Metro Station, and premium dining hubs.',
    locationDescription: 'Zero distance to Shilp Chowk Metro Station and Kharghar Central Market promenade.',
    keyHighlights: ['Direct Shilp Chowk Metro Gate Proximity', 'Ground & 1st Floor Premium High Street Retail', 'Full OC Received', 'Vitrified Large Slab Italian Look Tiles'],
    amenities: ['Rooftop Infinity Terrace Garden', 'Modern Gymnasium', 'High-Speed Elevators with Automatic Rescue Device', 'Multi-Tier Security'],
    coverImagePath: '/images/projects/shilp-residency-kharghar-11/cover.jpg',
    masterPlanPath: '/images/projects/shilp-residency-kharghar-11/masterplan.jpg',
    elevationImages: ['/images/projects/shilp-residency-kharghar-11/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/shilp-residency-kharghar-11/floorplan-2bhk.jpg', '/images/projects/shilp-residency-kharghar-11/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/shilp-residency-sec11.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec11-shilp-residency',
    units: [
      {
        unitNumber: '901',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 9,
        totalFloors: 17,
        carpetAreaSqft: 750,
        carpetAreaSqm: 69.68,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2022-12-31',
        agreementValue: 11400000,
        floorRiseCharges: 180000,
        parkingCharges: 350000,
        societyDevelopmentCharges: 210000,
        description: 'Prime Shilp Chowk avenue facing 2 BHK on 9th floor with high rental yield.',
        floorPlanPath: '/images/projects/shilp-residency-kharghar-11/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/shilp-residency-kharghar-11/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },
  {
    slug: 'mahaavir-heritage-kharghar-14',
    projectName: 'Mahaavir Heritage',
    developerName: 'Mahaavir Universal Homes',
    node: 'KHARGHAR',
    sector: 'Sector 14',
    microMarket: 'Kharghar Sector 14',
    subLocality: 'Jal Vayu Vihar Luxury Avenue',
    address: 'Plot 15, Sector 14, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000019870',
    reraApprovedDate: '2019-09-12',
    promoterLegalEntity: 'Mahaavir Superstructures Pvt Ltd',
    latitude: 19.0575,
    longitude: 73.0782,
    distanceToMetroKm: 0.2,
    nearestMetroStation: 'Sector 14 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-802',
    commencementCertificateDate: '2018-04-10',
    expectedPossessionDate: '2023-08-31',
    totalTowers: 2,
    totalFloors: 19,
    basePricePerSqft: 15500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Vikram Chheda',
    developerSalesPocPhone: '+919820234514',
    shortDescription: 'Twin G+19 towers on Sector 14 Metro interchange near Jal Vayu Vihar.',
    description: 'Mahaavir Heritage provides palatial 2 and 3 BHK residences overlooking Kharghar Central Lake and the CIDCO green belt in Sector 14.',
    locationDescription: 'Direct walking distance to Sector 14 Metro Station and prominent Kharghar hospitals.',
    keyHighlights: ['Twin High-Rise Architectural Elevation', '100% Lake & Green Belt View', 'Sector 14 Metro 150m Away', 'Full OC Received'],
    amenities: ['Grand Clubhouse', 'Semi-Olympic Pool', 'Children Splash Pool', 'Yoga Deck', 'Cardio Fitness Centre'],
    coverImagePath: '/images/projects/mahaavir-heritage-kharghar-14/cover.jpg',
    masterPlanPath: '/images/projects/mahaavir-heritage-kharghar-14/masterplan.jpg',
    elevationImages: ['/images/projects/mahaavir-heritage-kharghar-14/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/mahaavir-heritage-kharghar-14/floorplan-2bhk.jpg', '/images/projects/mahaavir-heritage-kharghar-14/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/mahaavir-heritage-sec14.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec14-mahaavir-heritage',
    units: [
      {
        unitNumber: 'A-1402',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 14,
        totalFloors: 19,
        carpetAreaSqft: 1120,
        carpetAreaSqm: 104.05,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-08-31',
        agreementValue: 17360000,
        floorRiseCharges: 280000,
        parkingCharges: 450000,
        societyDevelopmentCharges: 250000,
        description: 'Corner 3 BHK on 14th floor with 3 private balconies and uninterrupted lake sunrise view.',
        floorPlanPath: '/images/projects/mahaavir-heritage-kharghar-14/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/mahaavir-heritage-kharghar-14/elevation-1.jpg',
        isExclusive: true,
      },
    ],
  },
  {
    slug: 'hyde-park-kharghar-19',
    projectName: 'Hyde Park',
    developerName: 'Qualitas Real Estate',
    node: 'KHARGHAR',
    sector: 'Sector 19',
    microMarket: 'Kharghar Sector 19',
    subLocality: 'ISKCON Temple & Central Park North',
    address: 'Plot 28, Sector 19, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000016540',
    reraApprovedDate: '2018-05-10',
    promoterLegalEntity: 'Qualitas Buildcon Pvt Ltd',
    latitude: 19.0648,
    longitude: 73.0808,
    distanceToMetroKm: 0.3,
    nearestMetroStation: 'Central Park Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2021/OC-114',
    commencementCertificateDate: '2016-10-15',
    expectedPossessionDate: '2021-06-30',
    totalTowers: 4,
    totalFloors: 24,
    basePricePerSqft: 16500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Sameer Merchant',
    developerSalesPocPhone: '+919820234519',
    shortDescription: 'G+24 iconic luxury towers facing Central Park and ISKCON Temple.',
    description: 'Hyde Park Kharghar is one of Navi Mumbai’s most sought-after addresses, located right opposite the massive 290-acre Central Park and the monumental ISKCON Temple in Sector 19.',
    locationDescription: 'Fronting the 30-meter Central Park avenue, 300 meters from Central Park Metro Station.',
    keyHighlights: ['Direct Frontage to 290-Acre Central Park', 'Unobstructed ISKCON Temple Views', '75,000 Sq.Ft. Podium Leisure Deck', 'Full OC Received'],
    amenities: ['Resort Swimming Pool with Sun Decks', 'Multi-Court Sports Arena', 'Spa & Jacuzzi Suites', 'Mini Theatre', 'Banquet Hall for 300 Guests'],
    coverImagePath: '/images/projects/hyde-park-kharghar-19/cover.jpg',
    masterPlanPath: '/images/projects/hyde-park-kharghar-19/masterplan.jpg',
    elevationImages: ['/images/projects/hyde-park-kharghar-19/elevation-1.jpg', '/images/projects/hyde-park-kharghar-19/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/hyde-park-kharghar-19/floorplan-2bhk.jpg', '/images/projects/hyde-park-kharghar-19/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/hyde-park-sec19.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec19-hyde-park',
    units: [
      {
        unitNumber: 'C-1603',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 16,
        totalFloors: 24,
        carpetAreaSqft: 810,
        carpetAreaSqm: 75.25,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2021-06-30',
        agreementValue: 13365000,
        floorRiseCharges: 320000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 220000,
        description: 'High-floor 2 BHK with panoramic Central Park green canopy view and morning sun.',
        floorPlanPath: '/images/projects/hyde-park-kharghar-19/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/hyde-park-kharghar-19/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'D-2001',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 20,
        totalFloors: 24,
        carpetAreaSqft: 1260,
        carpetAreaSqm: 117.06,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2021-06-30',
        agreementValue: 20790000,
        floorRiseCharges: 400000,
        parkingCharges: 500000,
        societyDevelopmentCharges: 280000,
        description: 'Palatial 3 BHK with 3 master suites, servant quarters, and panoramic ISKCON temple & golf view.',
        floorPlanPath: '/images/projects/hyde-park-kharghar-19/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/hyde-park-kharghar-19/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },
  {
    slug: 'paradise-sai-marvel-kharghar-20',
    projectName: 'Paradise Sai Marvel',
    developerName: 'Paradise Group',
    node: 'KHARGHAR',
    sector: 'Sector 20',
    microMarket: 'Kharghar Sector 20',
    subLocality: 'Central Park & Golf View Luxury Avenue',
    address: 'Plot 10, Sector 20, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000018892',
    reraApprovedDate: '2019-07-22',
    promoterLegalEntity: 'Paradise Lifespaces LLP',
    latitude: 19.0625,
    longitude: 73.0838,
    distanceToMetroKm: 0.2,
    nearestMetroStation: 'Central Park Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-521',
    commencementCertificateDate: '2018-03-15',
    expectedPossessionDate: '2023-12-31',
    totalTowers: 2,
    totalFloors: 22,
    basePricePerSqft: 16800,
    standardCommissionPercent: 2.5,
    developerSalesPocName: 'Ritesh Wadhwa (Head Sales)',
    developerSalesPocPhone: '+919820234520',
    shortDescription: 'G+22 luxury towers with direct panoramic views of Kharghar 18-Hole Golf Course.',
    description: 'Paradise Sai Marvel is an ultra-luxury golf-facing development in Kharghar Sector 20, designed with grand double-height air-conditioned lobbies and high-end automated residences.',
    locationDescription: 'Overlooking the Kharghar Valley Golf Course, 200m from Central Park Metro Station.',
    keyHighlights: ['Direct 18-Hole Golf Course & Central Park View', 'Central Park Metro 200m', 'Full OC Received Ready Homes', '2 High-Speed Mitsubishi Elevators per Wing'],
    amenities: ['Skyline Infinity Swimming Pool', 'Golf Simulator Lounge', 'Fitness Centre with Steam/Sauna', 'Landscaped Podium Garden', 'Children Play Zone'],
    coverImagePath: '/images/projects/paradise-sai-marvel-kharghar-20/cover.jpg',
    masterPlanPath: '/images/projects/paradise-sai-marvel-kharghar-20/masterplan.jpg',
    elevationImages: ['/images/projects/paradise-sai-marvel-kharghar-20/elevation-1.jpg', '/images/projects/paradise-sai-marvel-kharghar-20/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/paradise-sai-marvel-kharghar-20/floorplan-2bhk.jpg', '/images/projects/paradise-sai-marvel-kharghar-20/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/sai-marvel-sec20.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec20-sai-marvel-tour',
    units: [
      {
        unitNumber: 'A-1502',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 15,
        totalFloors: 22,
        carpetAreaSqft: 835,
        carpetAreaSqm: 77.57,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 14028000,
        floorRiseCharges: 300000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 225000,
        description: 'Direct golf-facing 15th-floor 2 BHK with imported vitrified tile finish and large master deck.',
        floorPlanPath: '/images/projects/paradise-sai-marvel-kharghar-20/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/paradise-sai-marvel-kharghar-20/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'B-1801',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 18,
        totalFloors: 22,
        carpetAreaSqft: 1240,
        carpetAreaSqm: 115.20,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 20832000,
        floorRiseCharges: 360000,
        parkingCharges: 500000,
        societyDevelopmentCharges: 275000,
        description: 'Corner 3 BHK on 18th floor with dual view of Golf Course and Central Park.',
        floorPlanPath: '/images/projects/paradise-sai-marvel-kharghar-20/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/paradise-sai-marvel-kharghar-20/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },

  // =========================================================================
  // KHARGHAR - SECTORS 21 TO 33 (PETHPADA & MID-VALLEY RESIDENCES)
  // =========================================================================
  {
    slug: 'gami-emerald-kharghar-24',
    projectName: 'Gami Emerald',
    developerName: 'Gami Group',
    node: 'KHARGHAR',
    sector: 'Sector 24',
    microMarket: 'Kharghar Sector 24',
    subLocality: 'Owe Village Road & Pethpada Green Belt',
    address: 'Plot 14, Sector 24, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000028910',
    reraApprovedDate: '2021-08-14',
    promoterLegalEntity: 'Gami Housing Corporation',
    latitude: 19.0618,
    longitude: 73.0948,
    distanceToMetroKm: 0.7,
    nearestMetroStation: 'Pethpada Metro',
    hasOccupancyCertificate: false,
    commencementCertificateDate: '2021-02-10',
    expectedPossessionDate: '2025-12-31',
    totalTowers: 2,
    totalFloors: 18,
    basePricePerSqft: 13500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Prakash Gami',
    developerSalesPocPhone: '+919820234524',
    shortDescription: 'Under-construction G+18 high-rise towers in serene Sector 24 with modern amenities.',
    description: 'Gami Emerald provides contemporary 1 and 2 BHK apartments surrounded by the lush green Kharghar foothills and quick connectivity to Pethpada Metro.',
    locationDescription: 'Located near Sector 24 Sports Complex, 700 meters from Pethpada Metro Station.',
    keyHighlights: ['Eco-Friendly Modern Construction', 'Pethpada Metro Connectivity', 'Flexible Construction-Linked Payment Plans', 'Rooftop Lounge'],
    amenities: ['Swimming Pool with Sunken Deck', 'Air-Conditioned Gym', 'Rooftop Star Gazing Deck', 'Children Play Arena', 'Jogging Track'],
    coverImagePath: '/images/projects/gami-emerald-kharghar-24/cover.jpg',
    masterPlanPath: '/images/projects/gami-emerald-kharghar-24/masterplan.jpg',
    elevationImages: ['/images/projects/gami-emerald-kharghar-24/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/gami-emerald-kharghar-24/floorplan-1bhk.jpg', '/images/projects/gami-emerald-kharghar-24/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/gami-emerald-sec24.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec24-gami-emerald',
    units: [
      {
        unitNumber: 'A-602',
        bhk: 1,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 6,
        totalFloors: 18,
        carpetAreaSqft: 460,
        carpetAreaSqm: 42.73,
        facing: 'EAST',
        possessionStatus: 'UNDER_CONSTRUCTION',
        possessionDate: '2025-12-31',
        agreementValue: 6210000,
        floorRiseCharges: 120000,
        parkingCharges: 250000,
        societyDevelopmentCharges: 160000,
        description: 'East-facing 1 BHK in under-construction tower with attractive installment schedule.',
        floorPlanPath: '/images/projects/gami-emerald-kharghar-24/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/gami-emerald-kharghar-24/elevation-1.jpg',
      },
      {
        unitNumber: 'B-1004',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 10,
        totalFloors: 18,
        carpetAreaSqft: 690,
        carpetAreaSqm: 64.10,
        facing: 'NORTH_EAST',
        possessionStatus: 'UNDER_CONSTRUCTION',
        possessionDate: '2025-12-31',
        agreementValue: 9315000,
        floorRiseCharges: 200000,
        parkingCharges: 300000,
        societyDevelopmentCharges: 180000,
        description: 'Cross-ventilated 2 BHK with hill views and spacious modular kitchen space.',
        floorPlanPath: '/images/projects/gami-emerald-kharghar-24/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/gami-emerald-kharghar-24/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },
  {
    slug: 'regency-luxuria-kharghar-27',
    projectName: 'Regency Luxuria',
    developerName: 'Regency Group',
    node: 'KHARGHAR',
    sector: 'Sector 27',
    microMarket: 'Kharghar Sector 27',
    subLocality: 'Upper Hills View Enclave',
    address: 'Plot 18, Sector 27, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000025420',
    reraApprovedDate: '2020-11-20',
    promoterLegalEntity: 'Regency Nirman Ltd',
    latitude: 19.0708,
    longitude: 73.0998,
    distanceToMetroKm: 1.3,
    nearestMetroStation: 'Sector 34 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-311',
    commencementCertificateDate: '2019-09-15',
    expectedPossessionDate: '2024-03-31',
    totalTowers: 2,
    totalFloors: 16,
    basePricePerSqft: 12800,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Anil Agrawal',
    developerSalesPocPhone: '+919820234527',
    shortDescription: 'G+16 hill-facing towers in Kharghar Sector 27 with OC received.',
    description: 'Regency Luxuria offers premium 2 and 3 BHK homes tucked into the peaceful backdrop of Kharghar Hills in Sector 27.',
    locationDescription: 'Peaceful sector overlooking upper valley trails, 4 minutes from Sector 34 Metro Station.',
    keyHighlights: ['Unobstructed Kharghar Hill Scenery', 'OC Received Ready to Move', 'Spacious Room Dimensions', 'Low Pollution Green Belt'],
    amenities: ['Clubhouse with Gymnasium', 'Indoor Games Arena', 'Children Park', 'Designer Stilt Parking', 'Rainwater Harvesting'],
    coverImagePath: '/images/projects/regency-luxuria-kharghar-27/cover.jpg',
    masterPlanPath: '/images/projects/regency-luxuria-kharghar-27/masterplan.jpg',
    elevationImages: ['/images/projects/regency-luxuria-kharghar-27/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/regency-luxuria-kharghar-27/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/regency-luxuria-sec27.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec27-regency-luxuria',
    units: [
      {
        unitNumber: 'A-703',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 7,
        totalFloors: 16,
        carpetAreaSqft: 720,
        carpetAreaSqm: 66.89,
        facing: 'WEST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-03-31',
        agreementValue: 9216000,
        floorRiseCharges: 140000,
        parkingCharges: 300000,
        societyDevelopmentCharges: 175000,
        description: 'Sunset hill-facing 2 BHK with full ceramic tiling and large dry balcony.',
        floorPlanPath: '/images/projects/regency-luxuria-kharghar-27/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/regency-luxuria-kharghar-27/elevation-1.jpg',
      },
    ],
  },

  // =========================================================================
  // KHARGHAR - SECTORS 34 TO 40 (UPPER KHARGHAR MEGA-TOWNSHIP CORRIDOR)
  // =========================================================================
  {
    slug: 'juhi-niharika-kharghar-34',
    projectName: 'Juhi Niharika Mirage',
    developerName: 'Juhi Developers',
    node: 'KHARGHAR',
    sector: 'Sector 34',
    microMarket: 'Kharghar Sector 34',
    subLocality: 'Metro Hospital & Valley Entrance',
    address: 'Plot 2, Sector 34B, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000021489',
    reraApprovedDate: '2020-02-14',
    promoterLegalEntity: 'Juhi Developers Pvt Ltd',
    latitude: 19.0708,
    longitude: 73.0862,
    distanceToMetroKm: 0.2,
    nearestMetroStation: 'Sector 34 Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-492',
    commencementCertificateDate: '2019-01-10',
    expectedPossessionDate: '2023-10-31',
    totalTowers: 1,
    totalFloors: 14,
    basePricePerSqft: 14600,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Prashant Sukhadia',
    developerSalesPocPhone: '+919820234534',
    shortDescription: 'G+14 prime residential tower 150 meters from Sector 34 Metro Station.',
    description: 'Juhi Niharika Mirage Sector 34 stands at the entrance of the Upper Kharghar high-growth corridor with immediate metro connectivity and ready OC-approved units.',
    locationDescription: 'Opposite Metro Hospital station, walking distance to schools and local market.',
    keyHighlights: ['150 Meters from Sector 34 Metro', 'Full OC Received', 'Modern French Window Architecture', 'Spacious 2 BHK Planning'],
    amenities: ['Fitness Gym', 'Children Play Yard', 'Double Height Air-Conditioned Lobby', 'Automated Elevator Backup', 'Solar Common Lighting'],
    coverImagePath: '/images/projects/juhi-niharika-kharghar-34/cover.jpg',
    masterPlanPath: '/images/projects/juhi-niharika-kharghar-34/masterplan.jpg',
    elevationImages: ['/images/projects/juhi-niharika-kharghar-34/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/juhi-niharika-kharghar-34/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/juhi-niharika-sec34.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec34-juhi-niharika',
    units: [
      {
        unitNumber: '501',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 5,
        totalFloors: 14,
        carpetAreaSqft: 715,
        carpetAreaSqm: 66.42,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-10-31',
        agreementValue: 10439000,
        floorRiseCharges: 100000,
        parkingCharges: 350000,
        societyDevelopmentCharges: 190000,
        description: 'Vastu East 2 BHK with clear sunrise views and immediate OC possession.',
        floorPlanPath: '/images/projects/juhi-niharika-kharghar-34/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/juhi-niharika-kharghar-34/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },
  {
    slug: 'arihant-clan-aalishan-kharghar-35',
    projectName: 'Arihant Clan Aalishan',
    developerName: 'Arihant Superstructures',
    node: 'KHARGHAR',
    sector: 'Sector 35',
    microMarket: 'Kharghar Sector 35',
    subLocality: 'Amandoot Metro & Persian Architecture Belt',
    address: 'Plot 35, Sector 35D, Upper Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000006391',
    reraApprovedDate: '2017-08-10',
    promoterLegalEntity: 'Arihant Superstructures Ltd',
    latitude: 19.0738,
    longitude: 73.0882,
    distanceToMetroKm: 0.3,
    nearestMetroStation: 'Amandoot Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-290',
    commencementCertificateDate: '2016-12-05',
    expectedPossessionDate: '2024-04-30',
    totalTowers: 4,
    totalFloors: 53,
    basePricePerSqft: 15800,
    standardCommissionPercent: 2.5,
    developerSalesPocName: 'Gaurav Jain (Sales Director)',
    developerSalesPocPhone: '+919820234535',
    shortDescription: '4 Majestic 53-Storey Skyscraper Towers inspired by Persian Architecture.',
    description: 'Arihant Clan Aalishan in Kharghar Sector 35 is an ultra-luxury skyscraper landmark featuring 4 towers of 53 storeys, Persian Hammam baths, Sufiyana lounges, and direct proximity to Amandoot Metro.',
    locationDescription: 'Situated at Amandoot Metro Interchange in Sector 35, Upper Kharghar.',
    keyHighlights: ['53-Storey Iconic Skyscraper Elevations', 'Persian Themed Architecture & Sufiyana Lounge', 'Amandoot Metro 300m Away', 'Double-Height Entrance Lobbies with Crystal Chandeliers'],
    amenities: ['Persian Hammam Bath & Spa', 'Olympic Pool & Rain Dance Arena', 'Sufiyana Terrace Lounge', 'Squash Court', 'Mini Theatre', 'Aerobics Room'],
    coverImagePath: '/images/projects/arihant-clan-aalishan-kharghar-35/cover.jpg',
    masterPlanPath: '/images/projects/arihant-clan-aalishan-kharghar-35/masterplan.jpg',
    elevationImages: ['/images/projects/arihant-clan-aalishan-kharghar-35/elevation-1.jpg', '/images/projects/arihant-clan-aalishan-kharghar-35/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/arihant-clan-aalishan-kharghar-35/floorplan-2bhk.jpg', '/images/projects/arihant-clan-aalishan-kharghar-35/floorplan-3bhk.jpg', '/images/projects/arihant-clan-aalishan-kharghar-35/floorplan-4bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/arihant-aalishan-sec35.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec35-arihant-aalishan-53storey',
    units: [
      {
        unitNumber: 'T2-2403',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 24,
        totalFloors: 53,
        carpetAreaSqft: 795,
        carpetAreaSqm: 73.86,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-04-30',
        agreementValue: 12561000,
        floorRiseCharges: 480000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 240000,
        description: '24th floor 2 BHK in 53-storey skyscraper with breathtaking panoramic valley and skyline view.',
        floorPlanPath: '/images/projects/arihant-clan-aalishan-kharghar-35/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/arihant-clan-aalishan-kharghar-35/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'T3-3801',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 38,
        totalFloors: 53,
        carpetAreaSqft: 1220,
        carpetAreaSqm: 113.34,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-04-30',
        agreementValue: 19276000,
        floorRiseCharges: 760000,
        parkingCharges: 500000,
        societyDevelopmentCharges: 290000,
        description: 'Skyscraper 3 BHK on 38th floor with private Persian deck and unobstructed hill vista.',
        floorPlanPath: '/images/projects/arihant-clan-aalishan-kharghar-35/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/arihant-clan-aalishan-kharghar-35/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },
  {
    slug: 'sai-world-empire-kharghar-36',
    projectName: 'Sai World Empire',
    developerName: 'Paradise Group',
    node: 'KHARGHAR',
    sector: 'Sector 36',
    microMarket: 'Kharghar Sector 36',
    subLocality: 'Upper Kharghar Valley Road',
    address: 'Sai World Empire, Sector 36, Upper Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000026796',
    reraApprovedDate: '2020-09-28',
    promoterLegalEntity: 'Paradise Lifespaces LLP',
    latitude: 19.0765,
    longitude: 73.0898,
    distanceToMetroKm: 0.4,
    nearestMetroStation: 'Amandoot Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-188',
    commencementCertificateDate: '2019-06-15',
    expectedPossessionDate: '2024-12-31',
    totalTowers: 6,
    totalFloors: 49,
    basePricePerSqft: 16200,
    standardCommissionPercent: 2.5,
    developerSalesPocName: 'Sunil Punjabi (AVP Sales)',
    developerSalesPocPhone: '+919820234536',
    shortDescription: '18-Acre French & Roman Themed Luxury Township with 6 Iconic G+49 Skyscraper Towers.',
    description: 'Sai World Empire is Navi Mumbai’s most opulent 18-acre township in Kharghar Sector 36, featuring 6 grand 49-storey towers themed after the world’s greatest empires, the 75,000 sq.ft. Club Athena, and unmatched lifestyle amenities.',
    locationDescription: 'Prime Sector 36 Valley Road, 400 meters from Amandoot Metro Station.',
    keyHighlights: ['18-Acre Themed Luxury Township', '75,000 Sq.Ft. Royal Clubhouse (Club Athena)', '6 Towers of G+49 Storey Iconic Architecture', 'Olympic Sized Pools & Amphitheatre'],
    amenities: ['Club Athena Luxury Clubhouse', 'Wave Pool & Sunken Bar', 'Roman Amphitheatre', 'Indoor Squash & Badminton Courts', 'Banquet Ballroom', 'Zen Meditation Gardens'],
    coverImagePath: '/images/projects/sai-world-empire-kharghar-36/cover.jpg',
    masterPlanPath: '/images/projects/sai-world-empire-kharghar-36/masterplan.jpg',
    elevationImages: ['/images/projects/sai-world-empire-kharghar-36/elevation-1.jpg', '/images/projects/sai-world-empire-kharghar-36/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/sai-world-empire-kharghar-36/floorplan-2bhk.jpg', '/images/projects/sai-world-empire-kharghar-36/floorplan-3bhk.jpg', '/images/projects/sai-world-empire-kharghar-36/floorplan-4bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/sai-world-empire-sec36.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec36-sai-world-empire-township',
    units: [
      {
        unitNumber: 'Tower Caesar - 1802',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 18,
        totalFloors: 49,
        carpetAreaSqft: 860,
        carpetAreaSqm: 79.90,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-12-31',
        agreementValue: 13932000,
        floorRiseCharges: 360000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 250000,
        description: 'Imperial 2 BHK on 18th floor with grand Roman balcony and sunrise valley view.',
        floorPlanPath: '/images/projects/sai-world-empire-kharghar-36/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/sai-world-empire-kharghar-36/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'Tower Napoleon - 3201',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 32,
        totalFloors: 49,
        carpetAreaSqft: 1320,
        carpetAreaSqm: 122.63,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-12-31',
        agreementValue: 21384000,
        floorRiseCharges: 640000,
        parkingCharges: 500000,
        societyDevelopmentCharges: 300000,
        description: 'Palatial 3 BHK on 32nd floor with 3 wrap-around balconies and panoramic 18-acre township & hill view.',
        floorPlanPath: '/images/projects/sai-world-empire-kharghar-36/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/sai-world-empire-kharghar-36/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },
  {
    slug: 'adhiraj-capital-city-kharghar-37',
    projectName: 'Adhiraj Capital City',
    developerName: 'Adhiraj Constructions',
    node: 'KHARGHAR',
    sector: 'Sector 37',
    microMarket: 'Kharghar Sector 37',
    subLocality: 'Rohinjan & Mega-District Corridor',
    address: 'Adhiraj Capital City, Sector 37, Rohinjan, Kharghar, Navi Mumbai 410210',
    reraNumber: 'P52000048649',
    reraApprovedDate: '2022-04-18',
    promoterLegalEntity: 'Adhiraj Constructions Pvt Ltd',
    latitude: 19.0792,
    longitude: 73.0925,
    distanceToMetroKm: 0.6,
    nearestMetroStation: 'Amandoot Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-778',
    commencementCertificateDate: '2019-10-22',
    expectedPossessionDate: '2024-09-30',
    totalTowers: 7,
    totalFloors: 54,
    basePricePerSqft: 15400,
    standardCommissionPercent: 2.5,
    developerSalesPocName: 'Nitin Kadam (VP Sales)',
    developerSalesPocPhone: '+919820234537',
    shortDescription: 'Navi Mumbai’s largest 40-Acre Integrated Mega-District with G+54 Storey Skyscraper Towers.',
    description: 'Adhiraj Capital City is a 40-acre master-planned mega district in Kharghar Sector 37 featuring 54-storey skyscraper towers, a 6-acre private central park, Club Elysium, and world-class high-street retail.',
    locationDescription: 'Sector 37 Upper Kharghar off NH-48, 600m from Amandoot Metro Station.',
    keyHighlights: ['40-Acre Integrated Mega-District', '54-Storey Iconic Skyscraper Elevation', '6-Acre Private Central Park', 'Club Elysium 75,000 Sq.Ft. Clubhouse'],
    amenities: ['Club Elysium Mega Clubhouse', 'Olympic-Length Swimming Pool', '5-Tier Security System', 'Sky Lounge & Observation Deck', 'Tennis & Basketball Courts', 'Jogging Boulevard'],
    coverImagePath: '/images/projects/adhiraj-capital-city-kharghar-37/cover.jpg',
    masterPlanPath: '/images/projects/adhiraj-capital-city-kharghar-37/masterplan.jpg',
    elevationImages: ['/images/projects/adhiraj-capital-city-kharghar-37/elevation-1.jpg', '/images/projects/adhiraj-capital-city-kharghar-37/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/adhiraj-capital-city-kharghar-37/floorplan-1bhk.jpg', '/images/projects/adhiraj-capital-city-kharghar-37/floorplan-2bhk.jpg', '/images/projects/adhiraj-capital-city-kharghar-37/floorplan-3bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/adhiraj-capital-city-sec37.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=sec37-adhiraj-capital-city-54storey',
    units: [
      {
        unitNumber: 'Tower Meraki - 1404',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 14,
        totalFloors: 54,
        carpetAreaSqft: 755,
        carpetAreaSqm: 70.14,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-09-30',
        agreementValue: 11627000,
        floorRiseCharges: 280000,
        parkingCharges: 400000,
        societyDevelopmentCharges: 230000,
        description: 'Mid-rise 2 BHK in 54-storey skyscraper with 6-acre central park view and direct Metro access.',
        floorPlanPath: '/images/projects/adhiraj-capital-city-kharghar-37/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/adhiraj-capital-city-kharghar-37/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'Tower Oreka - 2802',
        bhk: 3,
        bathrooms: 3,
        balconies: 3,
        floorNumber: 28,
        totalFloors: 54,
        carpetAreaSqft: 1180,
        carpetAreaSqm: 109.62,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-09-30',
        agreementValue: 18172000,
        floorRiseCharges: 560000,
        parkingCharges: 500000,
        societyDevelopmentCharges: 280000,
        description: 'Sky-deck 3 BHK with 3 luxurious bathrooms, 28th-floor unobstructed mountain panorama, and smart home automation.',
        floorPlanPath: '/images/projects/adhiraj-capital-city-kharghar-37/floorplan-3bhk.jpg',
        elevationPath: '/images/projects/adhiraj-capital-city-kharghar-37/elevation-2.jpg',
        isExclusive: true,
      },
    ],
  },

  // =========================================================================
  // TALOJA PHASE 1 - SECTORS 1 TO 16
  // =========================================================================
  {
    slug: 'lodha-crown-taloja-phase-1',
    projectName: 'Lodha Crown Taloja',
    developerName: 'Lodha Group (Macrotech Developers)',
    node: 'TALOJA_PHASE_1',
    sector: 'Sector 4',
    microMarket: 'Taloja Phase 1 Sector 4',
    subLocality: 'Taloja Bypass Arterial Highway',
    address: 'Lodha Crown, Taloja Bypass Road, Sector 4, Taloja, Navi Mumbai 410208',
    reraNumber: 'P51700033960',
    reraApprovedDate: '2021-06-10',
    promoterLegalEntity: 'Macrotech Developers Limited',
    latitude: 19.0985,
    longitude: 73.1115,
    distanceToMetroKm: 1.8,
    nearestMetroStation: 'Pendhar Metro Terminal',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-319',
    commencementCertificateDate: '2020-01-15',
    expectedPossessionDate: '2023-12-31',
    totalTowers: 8,
    totalFloors: 14,
    basePricePerSqft: 7100,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Aditya Lodha (Sales Manager)',
    developerSalesPocPhone: '+919820234540',
    shortDescription: 'World-Class Township by Lodha with 1 & 2 BHK Quality Homes.',
    description: 'Lodha Crown Taloja is a premium master-planned township by the Lodha Group offering impeccably designed 1 and 2 BHK residences with dedicated bus shuttles to Dombivli and Taloja stations.',
    locationDescription: 'Prime Taloja Bypass Road, 5 minutes from Taloja Panchnand Railway Station.',
    keyHighlights: ['Brand Lodha Reliability & Construction Standards', 'Grand 25,000 Sq.Ft. Clubhouse', 'Dedicated Bus Shuttle to Railway & Metro Stations', 'Ready to Move with Full OC'],
    amenities: ['Grand Clubhouse with Swimming Pool', 'Gymnasium & Aerobics Studio', 'Ganesha Temple in Complex', 'Cricket Pitch & Multi-Play Court', '24/7 Security with ICMS'],
    coverImagePath: '/images/projects/lodha-crown-taloja-phase-1/cover.jpg',
    masterPlanPath: '/images/projects/lodha-crown-taloja-phase-1/masterplan.jpg',
    elevationImages: ['/images/projects/lodha-crown-taloja-phase-1/elevation-1.jpg', '/images/projects/lodha-crown-taloja-phase-1/elevation-2.jpg'],
    floorPlanImages: ['/images/projects/lodha-crown-taloja-phase-1/floorplan-1bhk.jpg', '/images/projects/lodha-crown-taloja-phase-1/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/lodha-crown-taloja.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-lodha-crown-tour',
    units: [
      {
        unitNumber: 'Tower 4 - 302',
        bhk: 1,
        bathrooms: 1,
        balconies: 1,
        floorNumber: 3,
        totalFloors: 14,
        carpetAreaSqft: 345,
        carpetAreaSqm: 32.05,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 2449500,
        floorRiseCharges: 0,
        parkingCharges: 200000,
        societyDevelopmentCharges: 125000,
        description: 'Optimum 1 BHK layout with maximum space utilization and zero wasted passage area.',
        floorPlanPath: '/images/projects/lodha-crown-taloja-phase-1/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/lodha-crown-taloja-phase-1/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'Tower 6 - 804',
        bhk: 2,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 8,
        totalFloors: 14,
        carpetAreaSqft: 475,
        carpetAreaSqm: 44.13,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-12-31',
        agreementValue: 3372500,
        floorRiseCharges: 100000,
        parkingCharges: 250000,
        societyDevelopmentCharges: 150000,
        description: 'Compact 2 BHK with 2 full bathrooms and garden view in Lodha Crown township.',
        floorPlanPath: '/images/projects/lodha-crown-taloja-phase-1/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/lodha-crown-taloja-phase-1/elevation-2.jpg',
      },
    ],
  },
  {
    slug: 'galaxy-orion-taloja-phase-1-sec6',
    projectName: 'Galaxy Orion',
    developerName: 'Galaxy Group',
    node: 'TALOJA_PHASE_1',
    sector: 'Sector 6',
    microMarket: 'Taloja Phase 1 Sector 6',
    subLocality: 'Central Phase 1 Gated Townships',
    address: 'Plot 8, Sector 6, Taloja Phase 1, Navi Mumbai 410208',
    reraNumber: 'P52000019234',
    reraApprovedDate: '2019-10-05',
    promoterLegalEntity: 'Galaxy Lifespaces LLP',
    latitude: 19.1028,
    longitude: 73.1075,
    distanceToMetroKm: 1.3,
    nearestMetroStation: 'Pendhar Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-411',
    commencementCertificateDate: '2018-06-12',
    expectedPossessionDate: '2023-08-31',
    totalTowers: 2,
    totalFloors: 15,
    basePricePerSqft: 7400,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Sunil Shinde',
    developerSalesPocPhone: '+919820234542',
    shortDescription: 'G+15 contemporary residential complex with ready OC homes in Taloja Phase 1.',
    description: 'Galaxy Orion delivers ready-to-move 1 and 2 BHK residences in the developed Sector 6 of Taloja Phase 1, minutes from shopping markets, schools, and transit links.',
    locationDescription: 'Situated in the prime residential core of Sector 6, 4 minutes from Pendhar Metro Station.',
    keyHighlights: ['Full OC Received Ready Possession', 'Earthquake Resistant Structure', 'Vastu Friendly Apartments', 'Podium Garden & Children Play Zone'],
    amenities: ['Fully Equipped Gymnasium', 'Community Hall', 'Intercom & CCTV Surveillance', 'High-Speed Elevators', 'Power Backup'],
    coverImagePath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/cover.jpg',
    masterPlanPath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/masterplan.jpg',
    elevationImages: ['/images/projects/galaxy-orion-taloja-phase-1-sec6/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/galaxy-orion-taloja-phase-1-sec6/floorplan-1bhk.jpg', '/images/projects/galaxy-orion-taloja-phase-1-sec6/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/galaxy-orion-taloja.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec6-galaxy-orion',
    units: [
      {
        unitNumber: 'A-502',
        bhk: 1,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 5,
        totalFloors: 15,
        carpetAreaSqft: 430,
        carpetAreaSqm: 39.95,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-08-31',
        agreementValue: 3182000,
        floorRiseCharges: 0,
        parkingCharges: 200000,
        societyDevelopmentCharges: 130000,
        description: 'East-facing 1 BHK with 2 bathrooms and ready OC in Taloja Sector 6.',
        floorPlanPath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'B-901',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 9,
        totalFloors: 15,
        carpetAreaSqft: 645,
        carpetAreaSqm: 59.92,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-08-31',
        agreementValue: 4773000,
        floorRiseCharges: 100000,
        parkingCharges: 250000,
        societyDevelopmentCharges: 160000,
        description: 'Spacious 2 BHK on 9th floor with garden view and cross-ventilation.',
        floorPlanPath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/galaxy-orion-taloja-phase-1-sec6/elevation-1.jpg',
      },
    ],
  },
  {
    slug: 'platinum-living-taloja-phase-1-sec11',
    projectName: 'Platinum Living',
    developerName: 'Platinum Group',
    node: 'TALOJA_PHASE_1',
    sector: 'Sector 11',
    microMarket: 'Taloja Phase 1 Sector 11',
    subLocality: 'Metro Gateway & High-Rise Belt',
    address: 'Plot 19, Sector 11, Taloja Phase 1, Navi Mumbai 410208',
    reraNumber: 'P52000024890',
    reraApprovedDate: '2021-03-20',
    promoterLegalEntity: 'Platinum Properties LLP',
    latitude: 19.1078,
    longitude: 73.0958,
    distanceToMetroKm: 0.6,
    nearestMetroStation: 'Pendhar Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-112',
    commencementCertificateDate: '2020-05-18',
    expectedPossessionDate: '2024-05-31',
    totalTowers: 2,
    totalFloors: 16,
    basePricePerSqft: 7600,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Naveen Jain',
    developerSalesPocPhone: '+919820234543',
    shortDescription: 'G+16 lifestyle towers 600m from Pendhar Metro Station in Sector 11.',
    description: 'Platinum Living offers elegantly finished 1 and 2 BHK residences with podium amenities in the rapid-growth Sector 11 of Taloja Phase 1.',
    locationDescription: 'Close to Pendhar Metro line, schools, and commercial shopping high street.',
    keyHighlights: ['600m from Pendhar Metro Station', 'Full OC Received', 'Modern Modular Kitchen Provision', 'High Quality Sanitary Fittings'],
    amenities: ['Gymnasium', 'Landscaped Garden', 'Jogging Track', 'Children Play Zone', 'CCTV Security'],
    coverImagePath: '/images/projects/platinum-living-taloja-phase-1-sec11/cover.jpg',
    masterPlanPath: '/images/projects/platinum-living-taloja-phase-1-sec11/masterplan.jpg',
    elevationImages: ['/images/projects/platinum-living-taloja-phase-1-sec11/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/platinum-living-taloja-phase-1-sec11/floorplan-1bhk.jpg', '/images/projects/platinum-living-taloja-phase-1-sec11/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/platinum-living-sec11.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec11-platinum-living',
    units: [
      {
        unitNumber: 'A-803',
        bhk: 1,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 8,
        totalFloors: 16,
        carpetAreaSqft: 440,
        carpetAreaSqm: 40.88,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-05-31',
        agreementValue: 3344000,
        floorRiseCharges: 0,
        parkingCharges: 200000,
        societyDevelopmentCharges: 135000,
        description: 'East-facing 1 BHK on 8th floor with ready OC and low maintenance.',
        floorPlanPath: '/images/projects/platinum-living-taloja-phase-1-sec11/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/platinum-living-taloja-phase-1-sec11/elevation-1.jpg',
      },
    ],
  },
  {
    slug: 'pendhar-metro-heights-taloja-phase-1-sec16',
    projectName: 'Pendhar Metro Heights',
    developerName: 'Today Global Developers',
    node: 'TALOJA_PHASE_1',
    sector: 'Sector 16',
    microMarket: 'Taloja Phase 1 Sector 16',
    subLocality: 'Pendhar Metro Station Hub',
    address: 'Plot 4, Sector 16, Pendhar Metro Hub, Taloja Phase 1, Navi Mumbai 410208',
    reraNumber: 'P52000027650',
    reraApprovedDate: '2021-07-15',
    promoterLegalEntity: 'Today Metro Buildcon LLP',
    latitude: 19.0972,
    longitude: 73.0878,
    distanceToMetroKm: 0.1,
    nearestMetroStation: 'Pendhar Metro Terminal',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-098',
    commencementCertificateDate: '2020-08-10',
    expectedPossessionDate: '2024-06-30',
    totalTowers: 1,
    totalFloors: 18,
    basePricePerSqft: 8500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Bhavin Patel',
    developerSalesPocPhone: '+919820234544',
    shortDescription: 'G+18 luxury tower 100 meters from Pendhar Metro Station Terminal.',
    description: 'Pendhar Metro Heights offers ultimate transit convenience situated directly at the terminus of Navi Mumbai Metro Line 1, bridging Taloja with Kharghar and Belapur in minutes.',
    locationDescription: 'Zero distance to Pendhar Metro Station, 2 minutes from Kharghar Sector 34.',
    keyHighlights: ['100 Meters to Pendhar Metro Terminal', 'Unmatched Rental Demand & Capital Appreciation', 'Grand Double Height Entrance Lobby', 'Full OC Received'],
    amenities: ['Skyline Fitness Studio', 'Rooftop Lounge', 'Automated Parking Stack', '24/7 Power Backup', 'Smart Card Access Control'],
    coverImagePath: '/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/cover.jpg',
    masterPlanPath: '/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/masterplan.jpg',
    elevationImages: ['/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/floorplan-1bhk.jpg', '/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/pendhar-metro-heights-sec16.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec16-pendhar-metro-heights',
    units: [
      {
        unitNumber: '1102',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 11,
        totalFloors: 18,
        carpetAreaSqft: 670,
        carpetAreaSqm: 62.24,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-06-30',
        agreementValue: 5695000,
        floorRiseCharges: 150000,
        parkingCharges: 250000,
        societyDevelopmentCharges: 160000,
        description: 'Metro-facing 2 BHK on 11th floor with immediate OC possession and high rental yield.',
        floorPlanPath: '/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/pendhar-metro-heights-taloja-phase-1-sec16/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },

  // =========================================================================
  // TALOJA PHASE 2 - SECTORS 21 TO 39
  // =========================================================================
  {
    slug: 'today-callisto-taloja-phase-2-sec21',
    projectName: 'Today Callisto',
    developerName: 'Today Global Developers',
    node: 'TALOJA_PHASE_2',
    sector: 'Sector 21',
    microMarket: 'Taloja Phase 2 Sector 21',
    subLocality: 'Phase 2 North Gateway',
    address: 'Plot 11, Sector 21, Taloja Phase 2, Navi Mumbai 410208',
    reraNumber: 'P52000029810',
    reraApprovedDate: '2021-11-18',
    promoterLegalEntity: 'Today Callisto LLP',
    latitude: 19.1128,
    longitude: 73.1098,
    distanceToMetroKm: 1.6,
    nearestMetroStation: 'Pendhar Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2024/OC-210',
    commencementCertificateDate: '2020-10-15',
    expectedPossessionDate: '2024-08-31',
    totalTowers: 3,
    totalFloors: 14,
    basePricePerSqft: 6500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Sameer Today',
    developerSalesPocPhone: '+919820234551',
    shortDescription: 'G+14 lifestyle township with 1 & 2 BHK residences in Taloja Phase 2 Sector 21.',
    description: 'Today Callisto is a well-planned gated community in Taloja Phase 2 Sector 21, offering landscaped recreational podiums, sports courts, and smart home provisions.',
    locationDescription: 'Phase 2 entrance sector, 5 minutes from CIDCO mass housing schemes and Metro link.',
    keyHighlights: ['Ready to Move with Full OC', 'Podium Lifestyle Amenities', 'Vastu Compliant Floor Plans', 'Low Maintenance Society Model'],
    amenities: ['Clubhouse with Gymnasium', 'Swimming Pool', 'Children Play Zone', 'Landscaped Garden', '24/7 Security'],
    coverImagePath: '/images/projects/today-callisto-taloja-phase-2-sec21/cover.jpg',
    masterPlanPath: '/images/projects/today-callisto-taloja-phase-2-sec21/masterplan.jpg',
    elevationImages: ['/images/projects/today-callisto-taloja-phase-2-sec21/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/today-callisto-taloja-phase-2-sec21/floorplan-1bhk.jpg', '/images/projects/today-callisto-taloja-phase-2-sec21/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/today-callisto-sec21.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec21-today-callisto',
    units: [
      {
        unitNumber: 'A-404',
        bhk: 1,
        bathrooms: 1,
        balconies: 1,
        floorNumber: 4,
        totalFloors: 14,
        carpetAreaSqft: 410,
        carpetAreaSqm: 38.09,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-08-31',
        agreementValue: 2665000,
        floorRiseCharges: 0,
        parkingCharges: 200000,
        societyDevelopmentCharges: 120000,
        description: 'Affordable 1 BHK in Phase 2 Sector 21 with ready OC and low stamp duty.',
        floorPlanPath: '/images/projects/today-callisto-taloja-phase-2-sec21/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/today-callisto-taloja-phase-2-sec21/elevation-1.jpg',
      },
      {
        unitNumber: 'B-702',
        bhk: 2,
        bathrooms: 2,
        balconies: 2,
        floorNumber: 7,
        totalFloors: 14,
        carpetAreaSqft: 615,
        carpetAreaSqm: 57.13,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2024-08-31',
        agreementValue: 3997500,
        floorRiseCharges: 80000,
        parkingCharges: 250000,
        societyDevelopmentCharges: 150000,
        description: 'Vastu North-East 2 BHK with garden facing balcony in Today Callisto.',
        floorPlanPath: '/images/projects/today-callisto-taloja-phase-2-sec21/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/today-callisto-taloja-phase-2-sec21/elevation-1.jpg',
        isHotDeal: true,
      },
    ],
  },
  {
    slug: 'arihant-anaika-taloja-phase-2-sec23',
    projectName: 'Arihant Anaika Phase 2',
    developerName: 'Arihant Superstructures',
    node: 'TALOJA_PHASE_2',
    sector: 'Sector 23',
    microMarket: 'Taloja Phase 2 Sector 23',
    subLocality: 'Ghot Camp & Modern Townships',
    address: 'Arihant Anaika, Sector 23, Taloja Phase 2, Navi Mumbai 410208',
    reraNumber: 'P52000017433',
    reraApprovedDate: '2018-11-20',
    promoterLegalEntity: 'Arihant Superstructures Ltd',
    latitude: 19.1168,
    longitude: 73.1058,
    distanceToMetroKm: 2.0,
    nearestMetroStation: 'Pendhar Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/BP/2023/OC-601',
    commencementCertificateDate: '2017-09-10',
    expectedPossessionDate: '2023-09-30',
    totalTowers: 4,
    totalFloors: 14,
    basePricePerSqft: 6600,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'Kailash Sharma',
    developerSalesPocPhone: '+919820234552',
    shortDescription: 'G+14 township with swimming pool, gym, and temple in Taloja Phase 2 Sector 23.',
    description: 'Arihant Anaika Phase 2 is an established gated residential community by Arihant Superstructures providing affordable luxury with club amenities in Sector 23.',
    locationDescription: 'Located on the main Ghot Camp artery in Taloja Phase 2.',
    keyHighlights: ['Reputed Developer (Arihant Superstructures)', 'Grand Temple within Complex', 'Ready OC Homes', 'Large Open Green Areas'],
    amenities: ['Swimming Pool', 'Air Conditioned Gym', 'Temple Enclave', 'Children Play Zone', 'Community Hall'],
    coverImagePath: '/images/projects/arihant-anaika-taloja-phase-2-sec23/cover.jpg',
    masterPlanPath: '/images/projects/arihant-anaika-taloja-phase-2-sec23/masterplan.jpg',
    elevationImages: ['/images/projects/arihant-anaika-taloja-phase-2-sec23/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/arihant-anaika-taloja-phase-2-sec23/floorplan-1bhk.jpg', '/images/projects/arihant-anaika-taloja-phase-2-sec23/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/arihant-anaika-sec23.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec23-arihant-anaika',
    units: [
      {
        unitNumber: 'Tower 2 - 601',
        bhk: 1,
        bathrooms: 1,
        balconies: 1,
        floorNumber: 6,
        totalFloors: 14,
        carpetAreaSqft: 425,
        carpetAreaSqm: 39.48,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-09-30',
        agreementValue: 2805000,
        floorRiseCharges: 0,
        parkingCharges: 200000,
        societyDevelopmentCharges: 125000,
        description: 'Vastu East 1 BHK with pool view in Arihant Anaika.',
        floorPlanPath: '/images/projects/arihant-anaika-taloja-phase-2-sec23/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/arihant-anaika-taloja-phase-2-sec23/elevation-1.jpg',
      },
    ],
  },
  {
    slug: 'cidco-swapnapurti-taloja-phase-2-sec28',
    projectName: 'CIDCO Swapnapurti High-Rise Cluster',
    developerName: 'CIDCO (City & Industrial Development Corp)',
    node: 'TALOJA_PHASE_2',
    sector: 'Sector 28',
    microMarket: 'Taloja Phase 2 Sector 28',
    subLocality: 'CIDCO Mass Housing Flagship 28',
    address: 'Sector 28, CIDCO Housing Township, Taloja Phase 2, Navi Mumbai 410208',
    reraNumber: 'P52000018560',
    reraApprovedDate: '2019-05-15',
    promoterLegalEntity: 'CIDCO Maharashtra Government',
    latitude: 19.1228,
    longitude: 73.0958,
    distanceToMetroKm: 1.9,
    nearestMetroStation: 'Pendhar Metro',
    hasOccupancyCertificate: true,
    ocCertificateNumber: 'CIDCO/HOUSING/2023/OC-990',
    commencementCertificateDate: '2018-01-20',
    expectedPossessionDate: '2023-06-30',
    totalTowers: 12,
    totalFloors: 14,
    basePricePerSqft: 6500,
    standardCommissionPercent: 2.0,
    developerSalesPocName: 'CIDCO Marketing Desk',
    developerSalesPocPhone: '+919820234553',
    shortDescription: 'Mega G+14 Planned Housing Complex by CIDCO with wide 24-meter roads in Sector 28.',
    description: 'CIDCO Swapnapurti Sector 28 is one of Navi Mumbai’s largest government-planned high-rise townships featuring broad tree-lined avenues, municipal water connections, and dedicated public garden plots.',
    locationDescription: 'Main Sector 28 CIDCO corridor, connected to Taloja Phase 2 central boulevard.',
    keyHighlights: ['Official CIDCO Planned Infrastructure', 'Wide 24m Avenues & Underground Utilities', '100% Clear Government Title & OC Received', 'Excellent Rental Demand from Industrial & IT Commuters'],
    amenities: ['Central Community Grounds', 'Children Play Parks', 'Municipal Water Pumping Station', 'Ample Open Parking', 'Commercial Shopping Arcade'],
    coverImagePath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/cover.jpg',
    masterPlanPath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/masterplan.jpg',
    elevationImages: ['/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/elevation-1.jpg'],
    floorPlanImages: ['/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/floorplan-1bhk.jpg', '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/floorplan-2bhk.jpg'],
    brochureUrl: 'https://zamzamproperties.in/brochures/cidco-sec28-taloja.pdf',
    youtubeWalkthroughUrl: 'https://youtube.com/watch?v=taloja-sec28-cidco-swapnapurti',
    units: [
      {
        unitNumber: 'Building 4 - 503',
        bhk: 1,
        bathrooms: 1,
        balconies: 1,
        floorNumber: 5,
        totalFloors: 14,
        carpetAreaSqft: 365,
        carpetAreaSqm: 33.91,
        facing: 'EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-06-30',
        agreementValue: 2372500,
        floorRiseCharges: 0,
        parkingCharges: 150000,
        societyDevelopmentCharges: 100000,
        description: 'Clean CIDCO resale 1 BHK unit with clear title, low maintenance, and open avenue view.',
        floorPlanPath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/floorplan-1bhk.jpg',
        elevationPath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/elevation-1.jpg',
        isHotDeal: true,
      },
      {
        unitNumber: 'Building 7 - 902',
        bhk: 2,
        bathrooms: 2,
        balconies: 1,
        floorNumber: 9,
        totalFloors: 14,
        carpetAreaSqft: 580,
        carpetAreaSqm: 53.88,
        facing: 'NORTH_EAST',
        possessionStatus: 'READY_TO_MOVE',
        possessionDate: '2023-06-30',
        agreementValue: 3770000,
        floorRiseCharges: 60000,
        parkingCharges: 180000,
        societyDevelopmentCharges: 120000,
        description: '2 BHK CIDCO layout with 2 bathrooms and separate drying area.',
        floorPlanPath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/floorplan-2bhk.jpg',
        elevationPath: '/images/projects/cidco-swapnapurti-taloja-phase-2-sec28/elevation-1.jpg',
      },
    ],
  },
];
