/**
 * Master Sector Definitions and Landmark Mapping for Kharghar & Taloja
 * Covers every single sector of Kharghar (1 to 40+) and Taloja (Phase 1 & Phase 2).
 */

export interface SectorDefinition {
  node: 'KHARGHAR' | 'TALOJA_PHASE_1' | 'TALOJA_PHASE_2';
  sectorNumber: string;
  displayName: string;
  zone: string;
  landmarks: string[];
  nearestMetroStation: string;
  distanceToMetroKm: number;
  averageRatePerSqft: number;
  centerCoordinates: {
    lat: number;
    lng: number;
  };
}

export const KHARGHAR_SECTORS: SectorDefinition[] = [
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 1',
    displayName: 'Kharghar Sector 1',
    zone: 'Station & Sion-Panvel Highway Gateway',
    landmarks: ['Kharghar Railway Station', 'Little World Mall', 'Belapur Creek'],
    nearestMetroStation: 'Belapur Terminal / Sector 7',
    distanceToMetroKm: 0.8,
    averageRatePerSqft: 13500,
    centerCoordinates: { lat: 19.0305, lng: 73.0645 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 2',
    displayName: 'Kharghar Sector 2',
    zone: 'Station Environs & Residential Enclave',
    landmarks: ['Railway Station East Entrance', 'CIDCO Garden Sector 2', 'NMMT Bus Terminus'],
    nearestMetroStation: 'Sector 7 Metro',
    distanceToMetroKm: 1.0,
    averageRatePerSqft: 13000,
    centerCoordinates: { lat: 19.0335, lng: 73.0672 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 3',
    displayName: 'Kharghar Sector 3',
    zone: 'Sion-Panvel Highway Facing Corridor',
    landmarks: ['Kharghar Flyover', 'Green View Hospital', 'Sector 3 Park'],
    nearestMetroStation: 'Sector 7 Metro',
    distanceToMetroKm: 1.1,
    averageRatePerSqft: 12800,
    centerCoordinates: { lat: 19.0365, lng: 73.0695 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 4',
    displayName: 'Kharghar Sector 4',
    zone: 'Ramsheth Thakur College & School Belt',
    landmarks: ['Ramsheth Thakur High School', 'Sector 4 Playground', 'Kharghar Medicity'],
    nearestMetroStation: 'Sector 7 Metro',
    distanceToMetroKm: 1.3,
    averageRatePerSqft: 12500,
    centerCoordinates: { lat: 19.0392, lng: 73.0688 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 5',
    displayName: 'Kharghar Sector 5',
    zone: 'Belpada Commercial & Transit Node',
    landmarks: ['Belpada Village', 'CIDCO Water Office', 'Green Meadows'],
    nearestMetroStation: 'Belpada / Sector 7 Metro',
    distanceToMetroKm: 0.4,
    averageRatePerSqft: 13200,
    centerCoordinates: { lat: 19.0418, lng: 73.0652 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 6',
    displayName: 'Kharghar Sector 6',
    zone: 'Parijat & Little World Commercial Zone',
    landmarks: ['Parijat Chowk', 'Glomax Mall', 'CIDCO Garden Sec 6'],
    nearestMetroStation: 'CIDCO Science Park Metro',
    distanceToMetroKm: 0.5,
    averageRatePerSqft: 13800,
    centerCoordinates: { lat: 19.0442, lng: 73.0678 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 7',
    displayName: 'Kharghar Sector 7',
    zone: 'Utsav Chowk Iconic Gateway',
    landmarks: ['Utsav Chowk Greek Amphitheatre', 'Bharti Vidyapeeth College', 'Balaji Temple Road'],
    nearestMetroStation: 'Utsav Chowk Metro',
    distanceToMetroKm: 0.2,
    averageRatePerSqft: 14500,
    centerCoordinates: { lat: 19.0465, lng: 73.0702 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 8',
    displayName: 'Kharghar Sector 8',
    zone: 'Bharti Vidyapeeth Educational Hub',
    landmarks: ['Bharti Vidyapeeth Institute of Technology', 'Kharghar Valley Golf Club Road'],
    nearestMetroStation: 'Utsav Chowk Metro',
    distanceToMetroKm: 0.7,
    averageRatePerSqft: 13600,
    centerCoordinates: { lat: 19.0492, lng: 73.0682 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 9',
    displayName: 'Kharghar Sector 9',
    zone: 'Tata Memorial Hospital & ACTREC Enclave',
    landmarks: ['Tata Memorial ACTREC Centre', 'Kharghar Hills Reserve', 'Kendriya Vihar'],
    nearestMetroStation: 'Sector 11 Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 13200,
    centerCoordinates: { lat: 19.0525, lng: 73.0665 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 10',
    displayName: 'Kharghar Sector 10',
    zone: 'Central Prime Residential Corridor',
    landmarks: ['Kharghar Post Office', 'Sector 10 Market', 'Ryan International School'],
    nearestMetroStation: 'Sector 11 Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 14000,
    centerCoordinates: { lat: 19.0512, lng: 73.0725 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 11',
    displayName: 'Kharghar Sector 11',
    zone: 'Shilp Chowk Prime High Street',
    landmarks: ['Shilp Chowk', 'Kharghar Police Station', 'D-Mart Central'],
    nearestMetroStation: 'Sector 11 Metro',
    distanceToMetroKm: 0.1,
    averageRatePerSqft: 15200,
    centerCoordinates: { lat: 19.0538, lng: 73.0752 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 12',
    displayName: 'Kharghar Sector 12',
    zone: 'Central Residential & Gated Communities',
    landmarks: ['Saraswati College of Engineering', 'Sector 12 Garden', 'Kharghar Plaza'],
    nearestMetroStation: 'Sector 11 Metro',
    distanceToMetroKm: 0.5,
    averageRatePerSqft: 14200,
    centerCoordinates: { lat: 19.0558, lng: 73.0721 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 13',
    displayName: 'Kharghar Sector 13',
    zone: 'Kopra Village & Central Enclave',
    landmarks: ['Kopra Bridge', 'Sector 13 Lake Garden', 'Anjuman-I-Islam College'],
    nearestMetroStation: 'Sector 14 Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 13500,
    centerCoordinates: { lat: 19.0585, lng: 73.0705 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 14',
    displayName: 'Kharghar Sector 14',
    zone: 'Jal Vayu Vihar Luxury Belt',
    landmarks: ['Jal Vayu Vihar Complex', 'Sector 14 Metro Interchange', 'Medicity Hospital'],
    nearestMetroStation: 'Sector 14 Metro',
    distanceToMetroKm: 0.2,
    averageRatePerSqft: 15500,
    centerCoordinates: { lat: 19.0572, lng: 73.0778 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 15',
    displayName: 'Kharghar Sector 15',
    zone: 'Kharghar Lake & Prime Park Facing',
    landmarks: ['Kharghar Central Lake', 'Sector 15 Promenade', 'Green Valley View'],
    nearestMetroStation: 'Sector 14 Metro',
    distanceToMetroKm: 0.8,
    averageRatePerSqft: 14800,
    centerCoordinates: { lat: 19.0602, lng: 73.0745 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 16',
    displayName: 'Kharghar Sector 16',
    zone: 'National Institute of Fashion Technology (NIFT)',
    landmarks: ['NIFT Campus', 'CIDCO Officers Enclave', 'Kharghar Hill Trails'],
    nearestMetroStation: 'Sector 14 Metro',
    distanceToMetroKm: 1.0,
    averageRatePerSqft: 14500,
    centerCoordinates: { lat: 19.0632, lng: 73.0718 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 17',
    displayName: 'Kharghar Sector 17',
    zone: 'Valley View & Executive Residences',
    landmarks: ['Valley View Park', 'Sector 17 High-Rise Cluster', 'Nature Trail Head'],
    nearestMetroStation: 'Sector 14 Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 13900,
    centerCoordinates: { lat: 19.0658, lng: 73.0692 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 18',
    displayName: 'Kharghar Sector 18',
    zone: 'Golf Course Perimeter & Hillside',
    landmarks: ['Golf Course Gate 3', 'Kharghar Hills Sanctuary', 'Green Crest'],
    nearestMetroStation: 'Central Park Metro',
    distanceToMetroKm: 1.1,
    averageRatePerSqft: 14800,
    centerCoordinates: { lat: 19.0682, lng: 73.0725 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 19',
    displayName: 'Kharghar Sector 19',
    zone: 'ISKCON Temple & Central Park North',
    landmarks: ['ISKCON Glory of Maharashtra Temple', 'Central Park Gate 2', 'Hyde Park'],
    nearestMetroStation: 'Central Park Metro',
    distanceToMetroKm: 0.3,
    averageRatePerSqft: 16500,
    centerCoordinates: { lat: 19.0645, lng: 73.0805 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 20',
    displayName: 'Kharghar Sector 20',
    zone: 'Central Park & Golf View Luxury Avenue',
    landmarks: ['Kharghar 18-Hole Golf Course', 'Central Park Amphitheatre', 'Paradise Sai Marvel'],
    nearestMetroStation: 'Central Park Metro',
    distanceToMetroKm: 0.2,
    averageRatePerSqft: 16800,
    centerCoordinates: { lat: 19.0622, lng: 73.0835 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 21',
    displayName: 'Kharghar Sector 21',
    zone: 'Kharghar Valley Golf Club Central',
    landmarks: ['Golf Club Clubhouse', 'Sector 21 Lake', 'CIDCO Luxury Bungalow Plots'],
    nearestMetroStation: 'Central Park Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 17200,
    centerCoordinates: { lat: 19.0595, lng: 73.0862 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 22',
    displayName: 'Kharghar Sector 22',
    zone: 'Pethpada Green Valley',
    landmarks: ['Pethpada Lake', 'CIDCO Mass Housing Plots', 'Green Horizon'],
    nearestMetroStation: 'Pethpada Metro',
    distanceToMetroKm: 0.4,
    averageRatePerSqft: 13800,
    centerCoordinates: { lat: 19.0565, lng: 73.0895 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 23',
    displayName: 'Kharghar Sector 23',
    zone: 'Pethpada Metro Corridor',
    landmarks: ['Pethpada Metro Station', 'Harmony School', 'Royal Palms'],
    nearestMetroStation: 'Pethpada Metro',
    distanceToMetroKm: 0.1,
    averageRatePerSqft: 14200,
    centerCoordinates: { lat: 19.0588, lng: 73.0922 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 24',
    displayName: 'Kharghar Sector 24',
    zone: 'Owe Village Road & High-Rise Corridor',
    landmarks: ['Owe Camp', 'Sector 24 Sports Complex', 'Gami Emerald'],
    nearestMetroStation: 'Pethpada Metro',
    distanceToMetroKm: 0.7,
    averageRatePerSqft: 13500,
    centerCoordinates: { lat: 19.0615, lng: 73.0945 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 25',
    displayName: 'Kharghar Sector 25',
    zone: 'Owe Hills & Valley Residences',
    landmarks: ['Owe Hills Foothills', 'Sector 25 Garden', 'Balaji Symphony Phase 1'],
    nearestMetroStation: 'Pethpada Metro',
    distanceToMetroKm: 1.0,
    averageRatePerSqft: 13200,
    centerCoordinates: { lat: 19.0642, lng: 73.0968 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 26',
    displayName: 'Kharghar Sector 26',
    zone: 'Green Crest & High-Rise Cluster',
    landmarks: ['Sector 26 CIDCO Complex', 'Valley Vista', 'Kharghar Hills Nature Park'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 12900,
    centerCoordinates: { lat: 19.0675, lng: 73.0982 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 27',
    displayName: 'Kharghar Sector 27',
    zone: 'Upper Hills View Enclave',
    landmarks: ['Hilltop Viewpoint', 'Sector 27 Park', 'Regency Luxuria'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 1.3,
    averageRatePerSqft: 12800,
    centerCoordinates: { lat: 19.0705, lng: 73.0995 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 28',
    displayName: 'Kharghar Sector 28',
    zone: 'Upper Valley Viewpoint',
    landmarks: ['Upper Kharghar Hills Reserve', 'Sector 28 Green Belt'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 1.4,
    averageRatePerSqft: 12700,
    centerCoordinates: { lat: 19.0732, lng: 73.0975 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 29',
    displayName: 'Kharghar Sector 29',
    zone: 'Upper Kharghar Residential Belt',
    landmarks: ['Sector 29 CIDCO Plots', 'Skyline Residency'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 12600,
    centerCoordinates: { lat: 19.0745, lng: 73.0945 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 30',
    displayName: 'Kharghar Sector 30',
    zone: 'Sector 30 High Street Corridor',
    landmarks: ['Sector 30 Commercial Strip', 'Metro Hospital Route'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 0.9,
    averageRatePerSqft: 13100,
    centerCoordinates: { lat: 19.0718, lng: 73.0915 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 31',
    displayName: 'Kharghar Sector 31',
    zone: 'Upper Kharghar Transit Node',
    landmarks: ['Sector 31 Ring Road', 'Pethpada Connect'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 0.8,
    averageRatePerSqft: 13300,
    centerCoordinates: { lat: 19.0688, lng: 73.0895 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 32',
    displayName: 'Kharghar Sector 32',
    zone: 'Upper Kharghar High-Rise Cluster',
    landmarks: ['Sector 32 Garden', 'Grand Residency'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 0.7,
    averageRatePerSqft: 13400,
    centerCoordinates: { lat: 19.0665, lng: 73.0872 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 33',
    displayName: 'Kharghar Sector 33',
    zone: 'Central Park West View',
    landmarks: ['Golf Course North Edge', 'Sector 33 Avenue'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 14100,
    centerCoordinates: { lat: 19.0682, lng: 73.0842 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 34',
    displayName: 'Kharghar Sector 34 (A/B/C/D/E)',
    zone: 'Metro Hospital & Valley Entrance',
    landmarks: ['Metro Hospital Station', 'Upper Kharghar Ring Road', 'Juhi Niharika'],
    nearestMetroStation: 'Sector 34 Metro',
    distanceToMetroKm: 0.2,
    averageRatePerSqft: 14600,
    centerCoordinates: { lat: 19.0705, lng: 73.0858 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 35',
    displayName: 'Kharghar Sector 35 (D/E/F/G/I)',
    zone: 'Arihant Clan & Luxury Skyscraper Corridor',
    landmarks: ['Arihant Clan Aalishan', 'Juhi Serenity', 'Amandoot Metro Interchange'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 0.3,
    averageRatePerSqft: 15800,
    centerCoordinates: { lat: 19.0735, lng: 73.0878 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 36',
    displayName: 'Kharghar Sector 36',
    zone: 'Sai World Empire & Mega Townships',
    landmarks: ['Sai World Empire 18-Acre Township', 'Upper Kharghar Hills Ring Road'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 0.4,
    averageRatePerSqft: 16200,
    centerCoordinates: { lat: 19.0762, lng: 73.0895 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 37',
    displayName: 'Kharghar Sector 37 / Rohinjan',
    zone: 'Adhiraj Capital City Mega District',
    landmarks: ['Adhiraj Capital City 40-Acre District', 'Rohinjan Metro Link'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 15400,
    centerCoordinates: { lat: 19.0788, lng: 73.0922 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 38',
    displayName: 'Kharghar Sector 38',
    zone: 'Upper Kharghar Valley Ridge',
    landmarks: ['Valley View Ridge', 'Kharghar Foothills Park'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 1.0,
    averageRatePerSqft: 14200,
    centerCoordinates: { lat: 19.0815, lng: 73.0945 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 39',
    displayName: 'Kharghar Sector 39',
    zone: 'Upper Kharghar North Boundary',
    landmarks: ['CIDCO High-End Layout 39', 'Valley Reserve'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 13900,
    centerCoordinates: { lat: 19.0838, lng: 73.0968 },
  },
  {
    node: 'KHARGHAR',
    sectorNumber: 'Sector 40',
    displayName: 'Kharghar Sector 40',
    zone: 'Upper Kharghar Terminal Node',
    landmarks: ['Upper Kharghar CIDCO Boundary', 'Nature Sanctuary Corridor'],
    nearestMetroStation: 'Amandoot Metro',
    distanceToMetroKm: 1.5,
    averageRatePerSqft: 13600,
    centerCoordinates: { lat: 19.0862, lng: 73.0988 },
  },
];

export const TALOJA_PHASE_1_SECTORS: SectorDefinition[] = [
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 1',
    displayName: 'Taloja Phase 1 Sector 1',
    zone: 'Taloja Railway Station Gateway',
    landmarks: ['Taloja Panchnand Railway Station', 'MIDC Commercial Hub'],
    nearestMetroStation: 'Pendhar Metro Terminal',
    distanceToMetroKm: 1.5,
    averageRatePerSqft: 6800,
    centerCoordinates: { lat: 19.0912, lng: 73.1045 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 2',
    displayName: 'Taloja Phase 1 Sector 2',
    zone: 'Station Environs & Mixed Residential',
    landmarks: ['Taloja Station East', 'Sector 2 Market'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.6,
    averageRatePerSqft: 6700,
    centerCoordinates: { lat: 19.0935, lng: 73.1065 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 3',
    displayName: 'Taloja Phase 1 Sector 3',
    zone: 'Taloja Bypass Arterial Corridor',
    landmarks: ['Taloja Bypass Highway', 'CIDCO Garden Sec 3'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.4,
    averageRatePerSqft: 6900,
    centerCoordinates: { lat: 19.0955, lng: 73.1085 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 4',
    displayName: 'Taloja Phase 1 Sector 4',
    zone: 'Ghot Village Road & Residential Hub',
    landmarks: ['Ghot Village Connect', 'Lodha Crown Taloja Phase 1 Link'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.8,
    averageRatePerSqft: 7100,
    centerCoordinates: { lat: 19.0982, lng: 73.1112 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 5',
    displayName: 'Taloja Phase 1 Sector 5',
    zone: 'Central Phase 1 Gated Townships',
    landmarks: ['Sector 5 Play Arena', 'CIDCO Residential Layout'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.5,
    averageRatePerSqft: 7200,
    centerCoordinates: { lat: 19.1005, lng: 73.1095 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 6',
    displayName: 'Taloja Phase 1 Sector 6',
    zone: 'Central Phase 1 Prime Residences',
    landmarks: ['Galaxy Carina & Orion Enclave', 'Sector 6 High Street'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.3,
    averageRatePerSqft: 7400,
    centerCoordinates: { lat: 19.1025, lng: 73.1072 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 7',
    displayName: 'Taloja Phase 1 Sector 7',
    zone: 'Phase 1 Market & Schools',
    landmarks: ['Taloja International School', 'Sector 7 Community Centre'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.2,
    averageRatePerSqft: 7300,
    centerCoordinates: { lat: 19.1045, lng: 73.1052 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 8',
    displayName: 'Taloja Phase 1 Sector 8',
    zone: 'CIDCO Mass Housing Node',
    landmarks: ['CIDCO Swapnapurti Housing Complex', 'Sector 8 Park'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.1,
    averageRatePerSqft: 7200,
    centerCoordinates: { lat: 19.1065, lng: 73.1035 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 9',
    displayName: 'Taloja Phase 1 Sector 9',
    zone: 'Kojro Road & Riverfront Corridor',
    landmarks: ['Kojro Road Bridge', 'Taloja Riverfront Garden'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.3,
    averageRatePerSqft: 7000,
    centerCoordinates: { lat: 19.1085, lng: 73.1015 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 10',
    displayName: 'Taloja Phase 1 Sector 10',
    zone: 'CIDCO Lottery & Affordable Housing Hub',
    landmarks: ['CIDCO Mega Housing Scheme Sec 10', 'Sector 10 Sports Ground'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.9,
    averageRatePerSqft: 7300,
    centerCoordinates: { lat: 19.1095, lng: 73.0985 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 11',
    displayName: 'Taloja Phase 1 Sector 11',
    zone: 'Metro Gateway & High-Rise Belt',
    landmarks: ['Metro Station Approach Road', 'Platinum Living'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.6,
    averageRatePerSqft: 7600,
    centerCoordinates: { lat: 19.1075, lng: 73.0955 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 12',
    displayName: 'Taloja Phase 1 Sector 12',
    zone: 'Central Transit Interchange',
    landmarks: ['Sector 12 Commercial Strip', 'City Park Taloja'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.5,
    averageRatePerSqft: 7700,
    centerCoordinates: { lat: 19.1055, lng: 73.0935 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 14',
    displayName: 'Taloja Phase 1 Sector 14',
    zone: 'Prime Metro Adjacent Sector',
    landmarks: ['Sector 14 Metro Promenade', 'CIDCO Valley View Complex'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.3,
    averageRatePerSqft: 8100,
    centerCoordinates: { lat: 19.1028, lng: 73.0915 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 15',
    displayName: 'Taloja Phase 1 Sector 15',
    zone: 'Pendhar & Kharghar Connectivity Corridor',
    landmarks: ['Pendhar Bridge', 'Kharghar Sector 34 Connect Road'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.4,
    averageRatePerSqft: 8200,
    centerCoordinates: { lat: 19.0998, lng: 73.0895 },
  },
  {
    node: 'TALOJA_PHASE_1',
    sectorNumber: 'Sector 16',
    displayName: 'Taloja Phase 1 Sector 16',
    zone: 'Pendhar Metro Station Hub',
    landmarks: ['Pendhar Metro Terminal Station', 'CIDCO Metro Depot Road'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 0.1,
    averageRatePerSqft: 8500,
    centerCoordinates: { lat: 19.0968, lng: 73.0875 },
  },
];

export const TALOJA_PHASE_2_SECTORS: SectorDefinition[] = [
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 21',
    displayName: 'Taloja Phase 2 Sector 21',
    zone: 'Phase 2 North Gateway & High-Rise Townships',
    landmarks: ['Sector 21 High Street', 'Today Global Township Link'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.6,
    averageRatePerSqft: 6500,
    centerCoordinates: { lat: 19.1125, lng: 73.1095 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 22',
    displayName: 'Taloja Phase 2 Sector 22',
    zone: 'Phase 2 Central Residential Hub',
    landmarks: ['Sector 22 CIDCO Layout', 'Green Garden'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.8,
    averageRatePerSqft: 6400,
    centerCoordinates: { lat: 19.1145, lng: 73.1075 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 23',
    displayName: 'Taloja Phase 2 Sector 23',
    zone: 'Ghot Camp & Modern Townships',
    landmarks: ['Ghot Camp Road', 'Arihant Anaika Phase 2 Link'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.0,
    averageRatePerSqft: 6600,
    centerCoordinates: { lat: 19.1165, lng: 73.1055 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 24',
    displayName: 'Taloja Phase 2 Sector 24',
    zone: 'Phase 2 Lake Environs',
    landmarks: ['Taloja Phase 2 Lake', 'Sector 24 Promenade'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.2,
    averageRatePerSqft: 6300,
    centerCoordinates: { lat: 19.1185, lng: 73.1035 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 25',
    displayName: 'Taloja Phase 2 Sector 25',
    zone: 'CIDCO Lottery Belt Phase 2',
    landmarks: ['CIDCO Mega Mass Housing 25', 'Community Hall'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.3,
    averageRatePerSqft: 6200,
    centerCoordinates: { lat: 19.1205, lng: 73.1015 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 26',
    displayName: 'Taloja Phase 2 Sector 26',
    zone: 'Phase 2 Commercial Strip',
    landmarks: ['Sector 26 Shopping Center', 'Phase 2 Bus Station'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.4,
    averageRatePerSqft: 6300,
    centerCoordinates: { lat: 19.1225, lng: 73.0995 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 27',
    displayName: 'Taloja Phase 2 Sector 27',
    zone: 'Koynavale & CIDCO Gated Scheme',
    landmarks: ['Koynavale Village', 'CIDCO Housing Lottery Tower Cluster'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.1,
    averageRatePerSqft: 6400,
    centerCoordinates: { lat: 19.1245, lng: 73.0975 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 28',
    displayName: 'Taloja Phase 2 Sector 28',
    zone: 'CIDCO Mass Housing Flagship 28',
    landmarks: ['CIDCO Sector 28 High-Rise Cluster', 'Sector 28 Central Ground'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.9,
    averageRatePerSqft: 6500,
    centerCoordinates: { lat: 19.1225, lng: 73.0955 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 29',
    displayName: 'Taloja Phase 2 Sector 29',
    zone: 'Phase 2 West Residential',
    landmarks: ['Sector 29 Garden', 'Valley View Complex'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.7,
    averageRatePerSqft: 6600,
    centerCoordinates: { lat: 19.1195, lng: 73.0935 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 30',
    displayName: 'Taloja Phase 2 Sector 30',
    zone: 'Metro Extension Proposed Belt',
    landmarks: ['Metro Line 12 Proposed Station', 'Sector 30 High Street'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.5,
    averageRatePerSqft: 6800,
    centerCoordinates: { lat: 19.1165, lng: 73.0915 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 31',
    displayName: 'Taloja Phase 2 Sector 31',
    zone: 'Phase 2 Prime Residential Corridor',
    landmarks: ['Sector 31 Park', 'Grand View Residences'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.3,
    averageRatePerSqft: 6900,
    centerCoordinates: { lat: 19.1135, lng: 73.0895 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 32',
    displayName: 'Taloja Phase 2 Sector 32',
    zone: 'Phase 2 South Boundary Connected to Kharghar',
    landmarks: ['Kharghar Link Expressway', 'Sector 32 Gated Colony'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 1.1,
    averageRatePerSqft: 7100,
    centerCoordinates: { lat: 19.1105, lng: 73.0875 },
  },
  {
    node: 'TALOJA_PHASE_2',
    sectorNumber: 'Sector 39',
    displayName: 'Taloja Phase 2 Sector 39',
    zone: 'CIDCO Lottery Megaproject Node',
    landmarks: ['CIDCO Sector 39 Lottery Housing', 'Koynavale East Park'],
    nearestMetroStation: 'Pendhar Metro',
    distanceToMetroKm: 2.2,
    averageRatePerSqft: 6300,
    centerCoordinates: { lat: 19.1265, lng: 73.0945 },
  },
];
